package main.server.response;

/**
 * Created by david on 2/19/15.
 */
public enum ResponseKind {
    ACCEPTEDCONNECTION,
    REFUSEDCONNECTION,
    ADDEDMESSAGE,
    FAILEDADDINGMESSAGE,
    DELETEDMESSAGE,
    FAILEDDELETEMESSAGE,
    MESSAGEREPLACED,
    ERRORREPLACINGMESSAGE,
    FETCHEDMESSAGE,
    FETCHEDMESSAGEFAILED,
    FETCHCOMPLETE,
    FAILEDFETCHCOMPLETE;
}
