package main.server.response;

public enum ResponseKind {
    ACCEPTEDCONNECTION,
    ADDEDMESSAGE,
    DELETEDMESSAGE,
    MESSAGEREPLACED,
    FETCHED,
    FETCHCOMPLETE,
    REFUSEDCONNECTION,
    ADDINGMESSAGE_FAILED,
    DELETEMESSAGE_FAILED,
    REPLACINGMESSAGE_FAILED,
    FETCHED_FAILED,
    FETCHCOMPLETE_FAILED
}
