package main;

/**
 * Created by david on 2/19/15.
 */
public enum ReturnKind {
    ACCEPTEDCONNECTION,
    REFUSEDCONNECTION,
    ADDEDMESSAGE,
<<<<<<< HEAD
    FAILEDADDINGMESSAGE,
    DELETEMESSAGE,
    FAILEDDELETEMESSAGE,
    MESSAGEREPLACED,
    ERRORREPLACINGMESSAGE,
    FETCHEDMESSAGE,
    FETCHEDMESSAGEFAILED,
    FETCHCOMPLETE,
    FAILEDFETCHCOMPLETE
    ;
=======
    FAILEDADDINGMESSAGE;
>>>>>>> fbace605cff6d5f6ac875381201c2e0ad748b0a8
}
