package main;

/**
 * Created by david on 2/19/15.
 */
public enum ReturnKind {
    ACCEPTEDCONNECTION,
    REFUSEDCONNECTION,
    ADDEDMESSAGE,
    FAILEDADDINGMESSAGE,
    DELETEMESSAGE,
    FAILEDDELETEMESSAGE,
    MESSAGEREPLACED,
    ERRORREPLACINGMESSAGE,
    FETCHEDMESSAGE,
    FETCHEDMESSAGEFAILED,
    FETCHCOMPLETE,
    FAILEDFETCHCOMPLETE;
}
